description: Heat Template - Linux User network
heat_template_version: '2018-08-31'
parameters:

  hostname:
    type: string
  image:
    type: string
  flavor:
    type: string
  user:
    type: string
  password:
    type: string

resources:

  linuxhosts:
    type: OS::Nova::Server
    properties:
      name: {get_param: hostname}
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
      - network: public
      user_data:
        str_replace:
          params:
            $user: {get_param : user}
            $password: {get_param : password}
          template: {get_file : "https://raw.githubusercontent.com/tra5hpanda/better-openstack/master/heat/host_scripts/linux.sh"}
      user_data_format: RAW