description: Heat Template - Windows User
heat_template_version: '2018-08-31'
parameters:

  hostname:
    type: string
  image:
    type: string
  flavor:
    type: string
  user:
    type: string
  password:
    type: string

resources:
  windowshosts:
    type: OS::Nova::Server
    properties:
      name: {get_param: hostname}
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
      - network: public
      user_data:
        str_replace:
          template: |
            #ps1_sysnative
             $ErrorActionPreference = 'SilentlyContinue'
             net user /add $user $password /y
             net localgroup administrators /add $user
             exit 1001
        params: 
          $user: { get_param: user }
          $password: { get_param: password }
      user_data_format: RAW