description: Heat Template - Windows User network 1
heat_template_version: '2018-08-31'
parameters:
  user:
    type: string
  password:
    type: string
  windowsimage:
    type: string
  windowsflavor:
    type: string

resources:
  windowshosts:
    type: OS::Nova::Server
    properties:
      name: windows_host
      image: {get_param: windowsimage}
      flavor: {get_param: windowsflavor}
      networks:
      - subnet: subnet3
      user_data:
        str_replace:
          params:
            $user: {get_param : user}
            $password: {get_param : password}
          template: {get_file : "https://raw.githubusercontent.com/tra5hpanda/better-openstack/master/heat/host_scripts/windows.ps1"}
      user_data_format: RAW