description: Heat Template - Linux User network
heat_template_version: '2018-08-31'
parameters:

  linux1image:
    type: string
  linux1flavor:
    type: string
  vulnport1: 
    type: number
  vulnport2: 
    type: number

resources:

  linuxhosts:
    type: OS::Nova::Server
    properties:
      name: linux1_host
      image: {get_param: linux1image}
      flavor: {get_param: linux1flavor}
      networks:
      - subnet: subnet1
      user_data:
            str_replace:
              template: |
                #!/bin/bash            
                echo 127.0.0.1 $(hostname) >> /etc/hosts
                export DEBIAN_FRONTEND=noninteractive
                # User Creation
                echo "CREATE USER"
                useradd user -m -U -s /bin/bash
                usermod -aG sudo user
                echo "root:SomethingSecret" | chpasswd
                echo "user:Security!" | chpasswd
                nc -l -p $openport1
                nc -l -p $openport2
              params: 
                $openport1: { get_param: vulnport1 }
                $openport2: { get_param: vulnport2 }
      user_data_format: RAW