description: Heat Template - Linux User network 1
heat_template_version: '2018-08-31'
parameters:

  linux2image:
    type: string
  linux2flavor:
    type: string
  vulnport3: 
    type: number
  vulnport4: 
    type: number

resources:

  linuxhosts:
    type: OS::Nova::Server
    properties:
      name: linux2_host
      image: {get_param: linux2image}
      flavor: {get_param: linux2flavor}
      networks:
      - subnet: subnet2
      user_data:
            str_replace:
              template: |
                #!/bin/bash            
                echo 127.0.0.1 $(hostname) >> /etc/hosts
                export DEBIAN_FRONTEND=noninteractive
                # User Creation
                echo "CREATE USER"
                useradd user -m -U -s /bin/bash
                usermod -aG sudo user
                echo "root:SomethingSecret" | chpasswd
                echo "user:Security!" | chpasswd
                nc -l -p $openport1
                nc -l -p $openport2
              params: 
                $openport1: { get_param: vulnport3 }
                $openport2: { get_param: vulnport4 }
      user_data_format: RAW
