description: Heat Template - Linux User network 1
heat_template_version: '2018-08-31'
parameters:
  user:
    type: string
  password:
    type: string
  linux2image:
    type: string
  linux2flavor:
    type: string
  vulnport3: 
    type: number
  vulnport4: 
    type: number

resources:

  linuxhosts:
    type: OS::Nova::Server
    properties:
      name: linux2_host
      image: {get_param: linux2image}
      flavor: {get_param: linux2flavor}
      networks:
      - subnet: subnet2
      user_data:
        str_replace:
          params:
            $user: {get_param : user}
            $password: {get_param : password}
            $openport3: { get_param: vulnport3 }
            $openport4: { get_param: vulnport4 }
          template: {get_file : "https://raw.githubusercontent.com/tra5hpanda/better-openstack/master/heat/host_scripts/linux2.sh"}
      user_data_format: RAW
